---
driver:
  name: vagrant
#  synced_folders:
#    - ["../../", "/vagrant", "create: true, type: :virtualbox"]

provisioner:
  name: chef_zero
  log_level: :info

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      box: ubuntu/bionic64
    server_wait: 30

suites:
  - name: master
    driver:
      customize:
        memory: 2048
        cpus: 2
      network:
        - ["private_network", {ip: "192.168.50.30"}]
    run_list:
      - recipe[kubernetes::docker]
      - recipe[kubernetes::kube_common]
      - recipe[kubernetes::kube_master]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/kube_common
        - test/integration/kube_master
    attributes:
  - name: node
    driver:
      customize:
        memory: 1024
        cpus: 1
      network:
        - ["private_network", {ip: "192.168.50.40"}]
    run_list:

      - recipe[kubernetes::docker]
      - recipe[kubernetes::kube_common]
      - recipe[kubernetes::kube_node]
    verifier:
      inspec_tests:
        - test/integration/default
        - test/integration/kube_common
    attributes: